name: tf-plan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

env:
  PLAN_BUCKET: plan-bucket-zaf
  PLAN_PREFIX: ${{ github.repository }}#${{ github.sha }}   # e.g. org/repo#<sha>
  # Optional if you don't hardcode backend in *.tf:
  # TF_BACKEND_CONFIG: "-backend-config=bucket=my-tf-state-bucket -backend-config=key=terraform.tfstate -backend-config=region=us-east-1 -backend-config=dynamodb_table=my-tf-locks"

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform 1.13.1
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO "https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip"
          unzip terraform_1.13.1_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan 
        run: terraform plan -input=false -out=plan.tfplan

      - name: Checksum plan
        run: sha256sum plan.tfplan | awk '{print $1}' > plan.tfplan.sha256

      - name: Upload plan & checksum to S3
        run: |
          aws s3 cp plan.tfplan "s3://${PLAN_BUCKET}/${PLAN_PREFIX}/plan.tfplan" --sse AES256
          aws s3 cp plan.tfplan.sha256 "s3://${PLAN_BUCKET}/${PLAN_PREFIX}/plan.tfplan.sha256" --sse AES256
